# Generated by Django 5.0.1 on 2024-01-31 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0002_alter_order_asset_id_alter_order_client_order_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='qty',
            field=models.FloatField(null=True),
        ),
    ]
