# Generated by Django 5.0.1 on 2024-01-27 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0002_alter_order_filled_qty_alter_order_qty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='subtag',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
