# Generated by Django 5.0.1 on 2024-01-27 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0003_alter_order_subtag'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='commission_bps',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
