# Generated by Django 5.0.1 on 2024-01-27 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='filled_qty',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='qty',
            field=models.FloatField(),
        ),
    ]
