# Generated by Django 5.0.1 on 2024-01-27 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0005_alter_order_commission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_class',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
